name: Python Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.runCommand({ping: 1})'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MongoDB to be ready
      run: |
        # Simple wait loop for MongoDB to be accessible
        for i in $(seq 1 10); do
          nc -z localhost 27017 && echo "MongoDB is up!" && break
          echo "Waiting for MongoDB..." && sleep 2
        done

    - name: Set up environment variables
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/CampusConnect" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "SECRET_KEY=your-secret-key" >> $GITHUB_ENV # Use a proper secret in production

    - name: Run tests
      run: |
        python -m unittest discover tests